### ISSUE TITLE
nOS download prompt Modal Design

### ISSUE THREAD

**Issue by fabric-8** [nos/website#9]
@mhuggins @deanpress I've created a [design for the modal which should show up if a user clicks a nOS url (Figma link)](https://www.figma.com/file/anLq4dwX3LR2VJ3Q8GLE3OYW/nOS-Marketing-Website?node-id=277%3A5957).

<img width="670" alt="modal" src="https://user-images.githubusercontent.com/4112698/47214266-a9638d00-d39d-11e8-9b14-6f6d0501eeab.png">

- Are you good with the design?
- @mhuggins Would you be ok with handling the implementation? 😬

**Comment by mhuggins** [comment]
Yep, I can take this!
